# Generated by Django 4.1.3 on 2023-02-26 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('profile_picture', models.URLField(null=True)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('close_friends', models.ManyToManyField(blank=True, null=True, related_name='close_friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
